# Generated by Django 2.2.12 on 2020-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_installing'),
    ]

    operations = [
        migrations.AddField(
            model_name='installing',
            name='order',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
