# Generated by Django 2.2.12 on 2020-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installing',
            name='order',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='order',
            field=models.BigIntegerField(default=0),
        ),
    ]
