# Generated by Django 2.2.12 on 2020-04-22 09:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200422_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='installing',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='0'),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
