# Generated by Django 2.2.12 on 2020-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200422_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installing',
            name='text',
            field=models.TextField(default='Sample Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Sample Text'),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='text',
            field=models.TextField(default='Sample Text'),
        ),
    ]
