# Generated by Django 2.2.12 on 2020-04-22 11:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200422_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('home', 'Home'), ('contact', 'Contact')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='Sample Text')),
                ('order', models.BigIntegerField(default=0)),
            ],
        ),
    ]
