# Generated by Django 2.2.12 on 2020-04-22 12:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='Sample Text')),
                ('order', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='installing',
            name='text',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='text',
        ),
    ]
