# Generated by Django 2.2.12 on 2020-04-23 02:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200422_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStarted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('callback', 'Choose callbacks'), ('env', 'Initialize environment'), ('result', 'Show results'), ('method', 'Initialize method'), ('train', 'Train model')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='Sample Text')),
                ('order', models.BigIntegerField(default=0)),
            ],
        ),
    ]
